FROM ubuntu:23.04

RUN apt-get update

RUN apt-get install -y vim less make git
RUN apt-get install -y python3 python3-pip python3-matplotlib python3-numpy python3-pandas  
RUN apt-get install -y python3-numba
RUN apt-get install -y x11-xserver-utils dbus-x11 xauth gedit
#RUN python3-pip install robotframework
