version : "3"

services: 
  dev-env:
    image: $CONTAINER_IMAGE_NAME:$BUILD_VER
    network_mode: "host"
    volumes:
      - ./:$WORKSPACE_DIR
    working_dir: $WORKSPACE_DIR
    environment:
      DISPLAY     : $DISPLAY
    container_name: $CONTAINER_INSTANCE_NAME
    # tty: true
    # stdin_open: true
    # healthcheck:
    #   disable: true
    entrypoint: ["bash" ,"-c", $ENTRY_COMMAND]
