version: "3"
services: 
  dev-env:
    image: build-env-scripts:0.1
    network_mode:  "host"
    volumes:
      - $WORKSPACE_DIR_HOST:$GO_WORKSPACE_DIR
      - /tmp/.X11-unix/:/tmp/.X11-unix/
    working_dir: $GO_WORKSPACE_DIR
    environment:
      DISPLAY     : $DISPLAY
    entrypoint: ["bash" ,"-c", "sleep infinity"]
